#!/usr/bin/env bash
# install nginx and start it 

apt-get update -y

# Install Nginx
apt-get install nginx -y

# Check if Nginx configuration file exists
if [ -f /etc/nginx/sites-available/default ]; then
    # Replace default server block configuration with custom configuration
    cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF
fi

# Restart Nginx service
service nginx restart
