#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 429608-web-01 52.3.68.204:80 check\n\tserver 429608-web-02 18.206.192.253:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
